name = "cc-bot-cf"
main = "index.js"
type = "javascript"
compatibility_date = "2024-06-01"


[vars]
TELEGRAM_BOT_TOKEN = "TOKEN_BOT"
ADMIN_USER_ID = "1234567890"
ADMIN_USERNAME = "username"
CHECK_CC_API_URL = "https://api.chkr.cc/"
